apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1 #  tells deployment to run 1 pod matching the template
  selector:
    matchLabels:
      app: eureka
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka-container
        image: registry.gitlab.com/gitlabodix/cvtheque-eureka-ms-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
      imagePullSecrets:
      - name: gitlab-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761

